In [4]:
import pandas as pd
daily_silver_on = pd.read_csv('Daily/silver_daily.csv').drop(columns=['DailyAvgOff'])

In [5]:
daily_silver_on

                        Stops  DailyAvgOn
0         Athletics Complex E       20.93
1         Athletics Complex W       25.40
2           Aux Services East       98.05
3           Aux Services West       66.50
4                    CRI Deck      213.48
5   Duke Centennial Hall East      193.71
6                      EPIC N      146.06
7                      EPIC S        8.02
8                 East Deck 2       19.08
9                  Fretwell N       89.32
10               Grigg Hall E      108.39
11               Grigg Hall W       32.14
12         Hickory Hall North        7.00
13                     Lot 5A      177.07
14                      Lot 6      170.27
15                Martin Hall      185.48
16               Motor Sports        8.34
17                PORTAL East       35.52
18                   Portal W      114.89
19            Robinson Hall S        0.01
20   Student Health (Green) W        0.00
21           Student Health E        2.50
22           Student Health N       33.35
23            Student Union E      309.12
24            Student Union W      454.38
25          Union Deck/Belk N        4.58
26   Wallis Hall E/Light Rail        8.42
27         Woodward Hall East       52.12
28       TOTAL USAGE AVERAGE:     2584.10